-- Estoque Visual Esquadrias
-- Estrutura-base do banco de dados.
-- Use apenas em um projeto Supabase novo. Não execute no banco atual.

create table if not exists public.fornecedores (
  id bigint generated by default as identity primary key,
  razao_social text not null,
  nome_fantasia text not null,
  categoria text not null,
  contato text,
  telefone text,
  whatsapp text,
  email text,
  cidade text,
  estado text,
  observacoes text,
  created_at timestamptz default now()
);

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  codigo text not null,
  descricao text,
  unidade text,
  quantidade bigint,
  estoque_minimo bigint,
  preco_compra numeric,
  observacao text,
  ultima_entrada timestamptz,
  fornecedor_id bigint,
  categoria text,
  excluido_em timestamptz
);

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nome text not null,
  login text not null unique,
  senha text,
  perfil text not null,
  ativo boolean default true,
  auth_user_id uuid unique references auth.users(id) on delete cascade
);

create table if not exists public.lixeira (
  id bigint generated by default as identity primary key,
  codigo text not null,
  descricao text not null,
  unidade text not null,
  quantidade integer not null,
  estoque_minimo integer not null,
  preco_compra numeric not null,
  observacao text,
  ultima_entrada timestamptz,
  data_exclusao timestamptz not null default now(),
  categoria text,
  fornecedor_id bigint,
  produto_id bigint
);

create table if not exists public.movimentacoes_estoque (
  id bigint generated by default as identity primary key,
  produto_id bigint not null,
  usuario_id bigint,
  tipo text not null,
  quantidade bigint not null,
  saldo_anterior bigint not null,
  saldo_resultante bigint not null,
  fornecedor_id bigint,
  preco_compra numeric,
  data_movimentacao timestamptz not null default now(),
  constraint movimentacoes_estoque_produto_id_fkey
    foreign key (produto_id) references public.produtos(id) on delete restrict,
  constraint movimentacoes_estoque_usuario_id_fkey
    foreign key (usuario_id) references public.usuarios(id) on delete set null,
  constraint movimentacoes_estoque_fornecedor_id_fkey
    foreign key (fornecedor_id) references public.fornecedores(id) on delete set null,
  constraint movimentacoes_estoque_quantidade_check check (quantidade > 0),
  constraint movimentacoes_estoque_tipo_check check (tipo = any (array['ENTRADA'::text, 'SAIDA'::text]))
);

create table if not exists public.entradas (
  id bigint generated always as identity primary key,
  codigo_produto text not null,
  fornecedor_id bigint,
  quantidade numeric not null,
  data_entrada timestamptz default now()
);

create table if not exists public.contas_pagar (
  id bigint generated always as identity primary key,
  data_lancamento date not null,
  favorecido text not null,
  descricao text not null,
  valor numeric not null,
  forma_pagamento text not null,
  data_vencimento date not null,
  status text not null default 'EM_ABERTO',
  observacoes text,
  created_at timestamptz default now(),
  data_pagamento date
);

create table if not exists public.vendas (
  id bigint generated always as identity primary key,
  data_venda date not null,
  cliente text not null,
  valor_total numeric not null,
  forma_pagamento text,
  responsavel text not null,
  status text not null default 'A_RECEBER',
  observacoes text,
  created_at timestamptz default now()
);

create table if not exists public.vendas_parcelas (
  id bigint generated always as identity primary key,
  venda_id bigint not null,
  numero_parcela integer not null,
  valor numeric not null,
  data_vencimento date,
  status text not null default 'A_RECEBER',
  created_at timestamptz default now(),
  total_parcelas integer not null default 1,
  condicionado_entrega boolean not null default false,
  descricao_entrega text,
  forma_pagamento text,
  constraint fk_venda foreign key (venda_id) references public.vendas(id) on delete cascade
);

create table if not exists public.vendas_recebimentos (
  id bigint generated always as identity primary key,
  parcela_id bigint not null,
  data_recebimento date not null,
  valor numeric not null,
  observacao text,
  created_at timestamptz default now(),
  constraint vendas_recebimentos_parcela_id_fkey
    foreign key (parcela_id) references public.vendas_parcelas(id) on delete cascade
);

