import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { testarCorrecaoDP } from './testar-correcao-dp.mjs';
process.on('uncaughtException',e=>{console.error('FALHA:',e.message,e.where??'',e.detail??'');process.exit(1);});
const db=new PGlite();
await db.exec(`create role authenticated; create role anon; create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('app.uid',true),'')::uuid$$;
 grant usage on schema public,auth to authenticated;
 grant all on all tables in schema auth to postgres;
`);
for(const f of fs.readdirSync('supabase/migrations').sort()) {
 if(!f.endsWith('.sql'))continue;
 if(f==='20260907_22_auditoria_dp.sql')await db.exec(`
 select set_config('app.restaurando_backup','true',false);
 insert into dp_funcionarios(id,nome,funcao,salario,data_admissao,ativo,data_inativacao) overriding system value values(900,'Histórico','Montador',3000,'2023-01-01',false,'2025-12-31');
 insert into dp_periodos_ferias(id,funcionario_id,periodo_aquisitivo_inicio,periodo_aquisitivo_fim,data_direito,limite_concessao) overriding system value values(900,900,'2023-01-01','2023-12-31','2024-01-01','2024-12-31');
 insert into dp_ferias(id,funcionario_id,periodo_id,inicio,fim,nome_funcionario,funcao_funcionario,valor_ferias,valor_terco,valor_abono,dias_gozo,abono_dias,data_prevista_pagamento,status,idempotencia) overriding system value values(900,900,900,'2024-03-01','2024-03-10','Histórico','Montador',1000,333.33,500,10,5,'2024-02-28','EM_ABERTO','99999999-1111-4111-8111-111111111111');
 insert into dp_ferias_pagamentos(ferias_id,componente,valor,data_pagamento,forma_pagamento,observacoes,idempotencia) values(900,'FERIAS',500,'2024-02-28','PIX','Pagamento parcial','99999999-1111-4111-8111-111111111112');
 select set_config('app.restaurando_backup','false',false);
 `);
 try { await db.exec(fs.readFileSync('supabase/migrations/'+f,'utf8')); console.log('Migration OK:',f); }
 catch(e){console.error('Migration FALHOU:',f,e.message);await db.close();process.exit(1);}
}
await db.exec(`insert into auth.users values('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002');
insert into usuarios(nome,login,perfil,ativo,auth_user_id) values('Desenvolvedor','dev','DESENVOLVEDOR',true,'00000000-0000-0000-0000-000000000001'),('Operador','op','OPERADOR',true,'00000000-0000-0000-0000-000000000002');
grant select on all tables in schema public to authenticated;
select set_config('app.uid','00000000-0000-0000-0000-000000000001',false);set role authenticated;`);
const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
const scalar=async(sql,args=[])=>(await q(sql,args))[0].v;
assert.equal(Number(await scalar(`select sum(quantidade_dias) v from dp_ferias_movimentacoes where periodo_id=900`)),15);
assert.equal(Number(await scalar(`select sum(valor) v from dp_ferias_movimentacoes where periodo_id=900`)),500);
assert.equal(await scalar(`select dp_quinto_dia_util('2026-04-01')::text v`),'2026-05-07');
assert.equal(await scalar(`select dp_quinto_dia_util('2026-05-01')::text v`),'2026-06-05');
assert.equal(await scalar(`select dp_quinto_dia_util('2026-08-01')::text v`),'2026-09-04');
const funcionario={nome:'Teste',funcao:'Montador',salario:3000,data_admissao:'2026-09-16',data_inativacao:null,ativo:true,observacoes:''};
const id=Number(await scalar(`select dp_salvar_funcionario($1) v`,[funcionario]));
await q(`select dp_gerar_folha('2026-09-01')`);
assert.equal(Number(await scalar(`select sum(valor) v from dp_pagamentos where funcionario_id=$1 and competencia='2026-09-01'`,[id])),1500);
await q(`select dp_gerar_folha('2026-09-01')`);
assert.equal(Number(await scalar(`select count(*) v from dp_pagamentos where funcionario_id=$1 and competencia='2026-09-01'`,[id])),2);
const pg=Number(await scalar(`select id v from dp_pagamentos where funcionario_id=$1 and competencia='2026-09-01' and tipo='ADIANTAMENTO'`,[id]));
await q(`select dp_lancar_ajuste($1,-100,'Falta','11111111-1111-4111-8111-111111111111')`,[pg]);
await q(`select dp_lancar_ajuste($1,-100,'Falta','11111111-1111-4111-8111-111111111111')`,[pg]);
assert.equal(Number(await scalar(`select valor_extra v from dp_pagamentos where id=$1`,[pg])),-100);
await assert.rejects(q(`select dp_lancar_ajuste($1,-99999,'Excesso','11111111-1111-4111-8111-111111111112')`,[pg]),/check/);
await assert.rejects(q(`select dp_salvar_funcionario($1,$2)`,[{...funcionario,ativo:false,data_inativacao:'2026-09-25'},id]),/Revise/);
await q(`select dp_salvar_funcionario($1,$2,$3)`,[{...funcionario,ativo:false,data_inativacao:'2026-09-25'},id,{'2026-09-01':'RECALCULAR'}]);
assert.equal(Number(await scalar(`select sum(valor) v from dp_pagamentos where funcionario_id=$1 and competencia='2026-09-01'`,[id])),1000);
const antigo=Number(await scalar(`select dp_salvar_funcionario($1) v`,[{...funcionario,nome:'Antigo',data_admissao:'2023-01-01'}]));
const per=Number(await scalar(`select id v from dp_periodos_ferias where funcionario_id=$1 order by id limit 1`,[antigo]));
const movimento={periodo_id:per,descricao:'Gozo',quantidade_dias:10,tipo_movimentacao:'GOZO',valor:0,data_movimentacao:'2026-09-01',observacoes:'',idempotencia:'11111111-1111-4111-8111-111111111113'};
await q(`select dp_salvar_movimento_ferias($1)`,[movimento]);
await q(`select dp_salvar_movimento_ferias($1)`,[movimento]);
await q(`select dp_salvar_movimento_ferias($1)`,[{...movimento,quantidade_dias:0,tipo_movimentacao:'PAGAMENTO_FERIAS',valor:1000,idempotencia:'11111111-1111-4111-8111-111111111114'}]);
assert.equal(Number(await scalar(`select sum(quantidade_dias) v from dp_ferias_movimentacoes where periodo_id=$1`,[per])),10);
await assert.rejects(q(`select dp_salvar_movimento_ferias($1)`,[{...movimento,quantidade_dias:21,idempotencia:'11111111-1111-4111-8111-111111111115'}]),/saldo/);
const conta={data_lancamento:'2026-09-01',favorecido:'Teste',descricao:'Teste',valor:50,forma_pagamento:'PIX',data_vencimento:'2026-09-01',observacoes:''};
const cid=Number(await scalar(`select salvar_conta_pagar($1) v`,[conta]));
await q(`select operar_conta_pagar($1,'PAGAR','2026-09-01')`,[cid]);
await assert.rejects(q(`select operar_conta_pagar($1,'CANCELAR')`,[cid]),/paga/);
assert(Number(await scalar(`select count(*) v from logs_financeiros`))>=2);
assert(Number(await scalar(`select count(*) v from dp_auditoria`))>0);
await db.exec(`reset role;alter table logs_financeiros add constraint teste_log_obrigatorio check(false) not valid;set role authenticated;`);
const antesFalha=Number(await scalar(`select count(*) v from contas_pagar`));
await assert.rejects(q(`select salvar_conta_pagar($1)`,[conta]),/teste_log_obrigatorio/);
assert.equal(Number(await scalar(`select count(*) v from contas_pagar`)),antesFalha);
await db.exec(`reset role;alter table logs_financeiros drop constraint teste_log_obrigatorio;
insert into fornecedores(id,razao_social,nome_fantasia,categoria) values(1,'Teste','Teste','Teste');
insert into produtos(id,codigo,quantidade,fornecedor_id) values(1,'P1',10,1);
insert into entradas(codigo_produto,fornecedor_id,quantidade) values('P1',1,10);
insert into movimentacoes_estoque(produto_id,usuario_id,tipo,quantidade,saldo_anterior,saldo_resultante,fornecedor_id) values(1,1,'ENTRADA',10,0,10,1);
insert into vendas(data_venda,cliente,valor_total,responsavel,status) values('2026-09-01','Cliente',100,'Teste','A_RECEBER');
insert into vendas_parcelas(venda_id,numero_parcela,valor,data_vencimento,forma_pagamento) values(1,1,100,'2026-09-01','PIX');
set role authenticated;select registrar_recebimento(1,'2026-09-01',30,'Parcial');`);
const backup=await scalar(`select gerar_backup_operacional('teste') v`);
const result=await scalar(`select restaurar_backup_completo($1) v`,[backup]);
assert.equal(result.sucesso,true);
const depois=await scalar(`select gerar_backup_operacional('teste') v`);
for(const t of Object.keys(backup.quantidades)) assert.deepEqual(depois[t],backup[t],t);
assert.equal(Number(await scalar(`select count(*) v from backup_seguranca`)),1);
const invalido=structuredClone(backup);delete invalido.entradas;
await assert.rejects(q(`select restaurar_backup_completo($1)`,[invalido]),/ausente/);
const fkInvalida=structuredClone(backup);fkInvalida.movimentacoes_estoque[0].produto_id=99999;
await assert.rejects(q(`select restaurar_backup_completo($1)`,[fkInvalida]),/foreign key/);
assert.equal(Number(await scalar(`select count(*) v from backup_seguranca`)),1);
assert.equal(Number(await scalar(`select quantidade v from produtos where id=1`)),10);
const semAuth=structuredClone(backup);semAuth.usuarios[0].auth_user_id='88888888-1111-4111-8111-111111111112';
await assert.rejects(q(`select restaurar_backup_completo($1)`,[semAuth]),/acesso|identidades/);
await q(`select restaurar_backup_completo($1)`,[{...backup,backupVersion:5}]);
const antigo4={...backup,backupVersion:4};delete antigo4.dp_ferias_movimentacoes;delete antigo4.entradas;delete antigo4.movimentacoes_estoque;delete antigo4.logs_financeiros;
await q(`select restaurar_backup_completo($1)`,[antigo4]);
assert.equal(Number(await scalar(`select count(*) v from movimentacoes_estoque`)),1);
await db.exec(`reset role;update logs_financeiros set created_at='2025-01-01';set role authenticated;`);
const lote=await scalar(`select exportar_logs_antigos('2025-02-01') v`);
assert(lote.quantidade>0);
await assert.rejects(q(`select confirmar_arquivo_logs($1,'inválido')`,[lote.lote]),/SHA/);
assert.equal(Number(await scalar(`select confirmar_arquivo_logs($1,$2) v`,[lote.lote,'a'.repeat(64)])),lote.quantidade);
assert.equal(Number(await scalar(`select confirmar_arquivo_logs($1,$2) v`,[lote.lote,'a'.repeat(64)])),0);
await q(`select set_config('app.uid','00000000-0000-0000-0000-000000000002',false)`);
assert.equal(Number(await scalar(`select count(*) v from dp_funcionarios`)),0);
await assert.rejects(q(`select gerar_backup_operacional('teste')`),/desenvolvedores/);
await assert.rejects(q(`select dp_lancar_ajuste($1,10,'indevido','11111111-1111-4111-8111-111111111116')`,[pg]),/Acesso/);
await assert.rejects(q(`update contas_pagar set valor=1 where id=$1`,[cid]),/permission/);
console.log('PASS: feriados, proporcional /30, idempotência, descontos, inativação, férias sem duplo desconto, logs, backup v6, importação v5, rollback e permissões.');
await testarCorrecaoDP(db);
await db.close();
